### ISSUE TITLE
Inconsistent time difference between update_no_mag and update_external_heading and examples

### ISSUE THREAD

**Issue by JanMH** [mark2b/imu-fusion-rs#2]
Currently there are some inconsistencies between the different functions and the examples because some functions expect an absolute timestamp in floats since time 0 whereas others expect a time difference.

For instance currently the simple example wouldn't work correctly since it is always passing the time difference between two measurements instead of the continuous timestamp.
```rs
        // ...
        fusion.update_no_mag(gyr, acc, 1.0 / SAMPLE_RATE_HZ as f32);
        // ...
```
whereas the fusion implementation expects a continuous float timestamp for update no mag

```rs
    pub fn update_no_mag(&mut self, gyr: FusionVector, acc: FusionVector, dt: f32) {
        let delta_t = dt - self.last_dt;
```

To clear up this confusion, I suggest to consistently always expect dt to be the time difference. Additionally, to make that behavior even more explicit, we could use the [core::Duration](https://doc.rust-lang.org/core/time/struct.Duration.html) type to encode this time difference.

I would be happy to give you a pull request if you agree to these changes.

**Comment by mark2b** [comment]
Hi, there are really inconsistencies in examples.
In my real project I use 
`
use embassy_time::driver::now;
`
`
let dt = now() as f32 / 1000000f32;
`
I prefer fix an examples. 
calculation delta inside of update makes it less error prone.

**Comment by JanMH** [comment]
For me it was problematic because I was passing unix timestamps in microseconds converted to floats but the precision of f32 was not enough to hold the significant bits of microseconds so I got weird results. That's why I believe the approach of passing the duration instead of the absolute timestamp might be less error prone.

I'm happy to give you a PR fixing the examples and update_external_heading if you still prefer the abslute timestamp approach though.

**Comment by mark2b** [comment]
Feel free to send PR
We can have two methods, for duration and for absolute time too.
Pay attention that inner ahrs implementation uses dt as seconds f32

**Comment by JanMH** [comment]
Excellent, I'm on it.

**Comment by JanMH** [comment]
This has been resolved by the two merged PRs
