### ISSUE TITLE
Access to internal fields

### ISSUE THREAD

**Issue by chamburr** [mark2b/imu-fusion-rs#5]
Hi, I'd really like to have access to more internal fields for advanced customisations. For instance, I want to use the FusionAhrs struct directly to bypass the offsets which I don't need in Fusion. I also want to dynamically change the gain value, so that recovery could be made faster when there is significant error from gyroscope.

Do you think we should expose all of the fields here? Otherwise, all I really need is for quaternion in FusionAhrs to be exposed.

https://github.com/mark2b/imu-fusion-rs/blob/3a47ccfb7bcfb3d0a71c785bb3910bec30c649de/src/lib.rs#L21-L51

Maybe exposing the offsets here in Fusion might be useful as well since they are given the default values and cannot be changed.

https://github.com/mark2b/imu-fusion-rs/blob/3a47ccfb7bcfb3d0a71c785bb3910bec30c649de/src/fusion_impl.rs#L8-L15

**Comment by mark2b** [comment]
Hi, feel free to make them public
